// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -verify -fopenmp -fopenmp-version=52 \
// RUN: -triple x86_64-unknown-linux -emit-llvm %s -o - | FileCheck %s

// expected-no-diagnostics

#ifndef HEADER
#define HEADER

void bar();


// CHECK-LABEL: define dso_local void @_Z27test_runtime_user_conditionb(
// CHECK-SAME: i1 noundef zeroext [[USE_GPU:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[USE_GPU_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[USE_GPU]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[USE_GPU_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[USE_GPU_ADDR]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP0]] to i1
// CHECK-NEXT:    br i1 [[LOADEDV]], label %[[OMP_META_THEN:.*]], label %[[OMP_META_ELSE:.*]]
// CHECK:       [[OMP_META_THEN]]:
// CHECK-NEXT:    call void @_Z3barv()
// CHECK-NEXT:    br label %[[OMP_META_END:.*]]
// CHECK:       [[OMP_META_ELSE]]:
// CHECK-NEXT:    call void (ptr, i32, ptr, ...) @__kmpc_fork_call(ptr @[[GLOB1:[0-9]+]], i32 0, ptr @.omp_outlined.)
// CHECK-NEXT:    br label %[[OMP_META_END]]
// CHECK:       [[OMP_META_END]]:
// CHECK-NEXT:    ret void
//
void test_runtime_user_condition(bool use_gpu) {
  #pragma omp metadirective \
      when(user={condition(use_gpu)}: target) \
      otherwise(parallel)
  {
    bar();
  }
}


// CHECK-LABEL: define dso_local void @_Z35test_runtime_user_condition_integeri(
// CHECK-SAME: i32 noundef [[THRESHOLD:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[THRESHOLD_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[THRESHOLD]], ptr [[THRESHOLD_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[THRESHOLD_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP0]], 100
// CHECK-NEXT:    br i1 [[CMP]], label %[[OMP_META_THEN:.*]], label %[[OMP_META_ELSE:.*]]
// CHECK:       [[OMP_META_THEN]]:
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label %[[FOR_COND:.*]]
// CHECK:       [[FOR_COND]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[TMP1]], 10
// CHECK-NEXT:    br i1 [[CMP1]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    call void @_Z3barv()
// CHECK-NEXT:    br label %[[FOR_INC:.*]]
// CHECK:       [[FOR_INC]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP2]], 1
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP4:![0-9]+]]
// CHECK:       [[FOR_END]]:
// CHECK-NEXT:    br label %[[OMP_META_END:.*]]
// CHECK:       [[OMP_META_ELSE]]:
// CHECK-NEXT:    call void (ptr, i32, ptr, ...) @__kmpc_fork_call(ptr @[[GLOB1]], i32 0, ptr @.omp_outlined..1)
// CHECK-NEXT:    br label %[[OMP_META_END]]
// CHECK:       [[OMP_META_END]]:
// CHECK-NEXT:    ret void
//
void test_runtime_user_condition_integer(int threshold) {



  #pragma omp metadirective \
      when(user={condition(threshold > 100)}: parallel for) \
      otherwise(parallel)
  {
    for (int i = 0; i < 10; ++i) {
      bar();
    }
  }
}

// CHECK-LABEL: define dso_local void @_Z33test_constant_user_condition_truev(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call void (ptr, i32, ptr, ...) @__kmpc_fork_call(ptr @[[GLOB1]], i32 0, ptr @_Z33test_constant_user_condition_truev.omp_outlined)
// CHECK-NEXT:    ret void
//
void test_constant_user_condition_true() {
  // For constant conditions, no runtime branch should be generated

  #pragma omp metadirective \
      when(user={condition(true)}: parallel) \
      otherwise(single)
  {
    bar();
  }
}

// CHECK-LABEL: define dso_local void @_Z34test_constant_user_condition_falsev(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(ptr @[[GLOB1]])
// CHECK-NEXT:    [[TMP1:%.*]] = call i32 @__kmpc_single(ptr @[[GLOB1]], i32 [[TMP0]])
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    br i1 [[TMP2]], label %[[OMP_IF_THEN:.*]], label %[[OMP_IF_END:.*]]
// CHECK:       [[OMP_IF_THEN]]:
// CHECK-NEXT:    call void @_Z3barv()
// CHECK-NEXT:    call void @__kmpc_end_single(ptr @[[GLOB1]], i32 [[TMP0]])
// CHECK-NEXT:    br label %[[OMP_IF_END]]
// CHECK:       [[OMP_IF_END]]:
// CHECK-NEXT:    call void @__kmpc_barrier(ptr @[[GLOB2:[0-9]+]], i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
void test_constant_user_condition_false() {
  // For constant conditions, no runtime branch should be generated

  #pragma omp metadirective \
      when(user={condition(false)}: parallel) \
      otherwise(single)
  {
    bar();
  }
}

#endif
//.
// CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]]}
// CHECK: [[META5]] = !{!"llvm.loop.mustprogress"}
//.
